[tools]
act = "latest"
chezmoi = "latest"
delta = "latest"
deno = "latest"
fzf = "latest"
ghq = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@charmland/crush" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:@qwen-code/qwen-code" = "latest"
"npm:opencode-ai" = "latest"
"npm:opencommit" = "latest"
"npm:serve" = "latest"
"npm:typescript-language-server" = "latest"
pnpm = "latest"
python = "3.12.6"
rclone = "latest"
ruby = "3.4.6"
rust = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true
